### PR TITLE
fix: Wrap microsite link in an LD flag

### PR DESCRIPTION
**Pull request by jcbcapps**
# SC-2372

## Proposed changes
Wrap link to microsite in an LD flag

---

## Reviewer notes
I wrapped the entire display in a flag, but let me know if I only need to wrap the `href` instead. I just thought it might be confusing to a screenreader if the jsx was still present but the `href` didn't go anywhere.

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

---

### As the original developer, I have

- [ ] Met the acceptance criteria
- [ ] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [ ] Followed guidelines for zero-downtime deploys, if applicable
- [ ] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

## Screenshots

false
true

### CODE REVIEW

**Comment by jbecker01** [comment]
This looks good locally. Should I test on dev at some point?

**Comment by jcbcapps** [comment]
> This looks good locally. Should I test on dev at some point?

@jbecker01 Maybe we should hold off on that? This PR will have to change once #1112 and #1107 are merged in.

**Review by gidjin — APPROVED** [review]
LGTM! I agree we should wrap the whole thing and not just the href.

**Comment by minhlai** [comment]
@mergify queue

**Comment by minhlai** [comment]
@mergifyio queue

**Comment by gidjin** [comment]
Replaced by work in #1112

**Pull request closed without merging**
