### PR TITLE
dev: Remove embedded Keystone and related files

### PR DESCRIPTION
**Pull request by suzubara**
# SC-294

## Proposed changes

This PR completes the migration to hosted Keystone, by removing embedded Keystone from the portal client.

---

## Reviewer notes

Only regression testing is needed. There should be no user-facing changes.
- The `/keystone-test` page should no longer be available.
- If you log in as a CMS admin, you should be able to make changes to Collections & Bookmarks and see them immediately reflected in the portal app.

## Setup

- Check out this branch
- Clean install of node modules: `rm -rf node_modules && yarn install`
- Start up services & CMS: `yarn cms:up` (make sure you have the CMS repo checked out, on the main branch, and up-to-date)
- Start up the portal app: `yarn build && yarn start`

---

### As the original developer, I have

- [ ] Met the acceptance criteria, or will meet them in subsequent PRs or stories
- [ ] Created/modified automated E2E tests in Cypress

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a test user, I have

- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
  - [ ] On commercial internet in IE11
  - [x] On commercial internet in Firefox
  - [x] On commercial internet in Chrome
  - [ ] On commercial internet in Safari
  - [ ] On NIPR in IE11
  - [ ] On NIPR in Firefox
  - [ ] On NIPR in Chrome
  - [ ] On NIPR in Safari
  - [ ] On a mobile device in Firefox
  - [ ] On a mobile device in Chrome
  - [ ] On a mobile device in Safari
- [ ] Added any anomalous behavior to this PR

### CODE REVIEW

**Comment by abbyoung** [comment]
I didn't experience any of the issues @jcbcapps did, so not sure what's happening.

Was able to successfully add a new collection in CMS and see it reflected on sites & apps, and can no longer access keystone-test. 🌈 ⭐

**Comment by suzubara** [comment]
@jcbcapps the env vars defined in the CMS docker compose file were out of date! that's what I get for not testing my own instructions 🙃  it should be fixed now!

**Review by jcbcapps — APPROVED** [review]
Looks great!

**Review by jbecker01 — APPROVED** [review]
👍

**Review by abbyoung — APPROVED** [review]

**Review by jbecker01 — APPROVED** [review]
looks good

**Pull request merged**
