### PR TITLE
feat: Maximum links UI

### LINKED ISSUE #439: Maximum links per collection (10)
Limit users from adding more than 10 links to a collection in My Space.

- Need UX designed communicating this limit to the user
- Need error state if user attempts to do this anyways

### PR DESCRIPTION
**Pull request by suzubara**
## Description 

This PR enforces the limit of 10 links per collection in the UI:

*  When adding a link, if the collection already has 9 links, a warning is displayed to the user to let them know they are about to reach the limit of 10
* If a collection has 10 links, the Add Link button is hidden to prevent a user from adding any more

Fixes #439 

## Review Notes

Screen Shot 2022-02-02 at 12 52 22 PM
image

### CODE REVIEW

**Comment by suzubara** [comment]
Hold on https://github.com/USSF-ORBIT/ussf-portal-client/pull/487

**Comment by kategarklavs** [comment]
@suzubara Hey! I've come up with two potential alternatives for the tooltip text — feel free to choose whichever one you all prefer (or if you don't like either of these, I can come up with other alternatives):

Potential option 1: "You've almost reached the limit of 10 links for this collection."

Potential option 2: "You're about to hit your link limit — each collection can only have 10 links."

**Comment by MKDale** [comment]
Option 2 resonates more for me. I like the explicit mention that they're currently at 9 and about to hit 10. The word "almost" for me in Option 1 is a bit too fuzzy.

**Review by jbecker01 — APPROVED** [review]
Looks good

**Review by esacteksab — APPROVED** [review]

**Pull request merged**
