### PR TITLE
chore: design: adds new portal logo to the site footer

### PR DESCRIPTION
**Pull request by shkeating**
# SC-2521

## Proposed changes

This branch... 
- swaps in our new logo for the portal into the site footer
- removes the space force delta and the `Made by ORBIT with ❤️` button
- new logo still links the user to the github pages site, which will be updated in a subsequent branch
- adds js so the year printed will auto-update
- adjusts styles to accomodate for the different shape/colors present in the left column of the footer

## Reviewer notes

I haven't had a chance to assess impacts to tests yet, will peek at that tomorrow

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000, scroll on down to the footer and check it out

### Start storybook

```sh
yarn storybook
```
http://localhost:3000/?path=/story/navigation-footer--default-footer

---

### As the original developer, I have

- [x] Met the acceptance criteria
- [x] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [x] Followed guidelines for zero-downtime deploys, if applicable
- [x] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

## Screenshots

image

### CODE REVIEW

**Comment by AnnaGingle** [comment]
Just took a look at this now. The foot looks really big. What do you think about adjusting the logo `max-height` & `max-width` to match the height
Screenshot 2023-10-04 at 9 51 42 AM
Screenshot 2023-10-04 at 9 52 05 AM
 of the links?

**Comment by shkeating** [comment]
@AnnaGingle yeah u right it is lorge I just scaled it down

**Review by AnnaGingle — APPROVED** [review]
Great work!

**Review by jcbcapps — APPROVED** [review]

**Review by abbyoung — APPROVED** [review]

**Comment by shkeating** [comment]
@jcbcapps @abbyoung @gidjin I'm getting a lint test failure for test coverage 🤔

**Comment by minhlai** [comment]
@mergify enqueue

**Comment by minhlai** [comment]
@mergify queue

**Comment by minhlai** [comment]
@mergifyio requeue

**Pull request merged**
