### PR TITLE
fix: a11y: heading elements usage and ordering 

### PR DESCRIPTION
**Pull request by shkeating**
# SC-2310

## Proposed changes

In accordance with the [Trusted Tester 10: Content](https://section508coordinators.github.io/TrustedTester/structure.html) Test IDs

- changes page templates and components that hold the page title to use a h1 for the heading element containing the name of the page
- removes h2 designation from the `Welcome, $name` `Personal Data` component, as well as the preview for it to not use a header element. This h2 ussage was not correct and broke the header order
- adjusts the headings on components to use the next sequential header (widget headers are now h2s, and the heading below them are h3, h4, etc.
- ensures header styling is correct and in alignment with how they were designed. Widget headers are bold, and some size corrections were made in the weather widget

**TO DO: fix all the unit tests this affects :')**

## Reviewer notes

there are design system implications to this change. both in figma and storybook we need to make adjustments to our design tokens to reflect different font sizes being assigned to the h2/h3 elements than initally anticipates

this PR changes the semantic output of these elements, and if visual changes were made they were done in accordance with Figma designs, details I think may have been missed when they are first styles (for example Widget headers being bold)

e2e tests: https://github.com/USSF-ORBIT/ussf-portal/pull/371

## Setup

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

## Screenshots

image

image

image

### CODE REVIEW

**Review by AnnaGingle — APPROVED** [review]
This is good to go! 💫

**Comment by AnnaGingle** [comment]
I have a couple of heading levels I want to double-check on. 

**USSF documentation**: The accordion header is H2 and it just looks off to me. Also, the footer H2s are smaller and visually proportional. Can we update the styling of the accordion's H2s?

**Review by AnnaGingle — APPROVED** [review]
Everything is good to go within the scope of this pr!

**Comment by shkeating** [comment]
> I have a couple of heading levels I want to double-check on.
> ### **USSF documentation**
> 
> The accordion header is H2 and it just looks off to me. Also, the footer H2s are smaller and visually proportional. Can we update the styling of the accordion's H2s?
> ### **My Space**
> 
> The collection header is not visually an h2. I think this fails 1.3.1-heading-level.

1.3.1 means that h2s are less visually prominent than h1s and more visaully promient than h3s. based on that, this would pass. I do think we need to update the design system docs in storybook to reflect the changes in what an h1-h5 is though.

**Review by AnnaGingle — APPROVED** [review]

**Review by gidjin — APPROVED** [review]

**Pull request merged**
