### PR TITLE
feat: Drag and drop support for links within a collection

### PR DESCRIPTION
**Pull request by jcbcapps**
# SC-154

## Proposed changes

- A user is is able to re-arrange links (canonical and custom) within a collection via drag and drop

## Setup

To test:
- Run `yarn services:up` in your local directory
- Run ussf-portal-cms locally with `yarn dev`
- Pull down this branch and run locally with `yarn dev`
- Login and while viewing My Space, verify that you can see the icon to the left of each link in a collection.
- Click and hold the icon while dragging the link to a new position within the collection. Verify that the newly moved link remains where you dropped it.
- Refresh the page and verify that the new order of the links persists.
---

### As the original developer, I have

- [ ] Created/modified automated unit tests in Jest
  - [ ] Including jest-axe checks when UI changes
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)
- [ ] Requested a design review for user-facing changes

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a designer reviewer, I have

- [ ] Checked in the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a test user, I have

- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
  - [ ] On commercial internet in IE11
  - [x] On commercial internet in Firefox
  - [x] On commercial internet in Chrome
  - [x] On commercial internet in Safari
  - [ ] On NIPR in IE11
  - [ ] On NIPR in Firefox
  - [ ] On NIPR in Chrome
  - [ ] On NIPR in Safari

### CODE REVIEW

**Review by suzubara — CHANGES_REQUESTED** [review]
Tested the drag & drop functionality locally, that looks really good! I am wondering if there's a way to smooth over the small jump that happens on drag end, but if that's not straightforward I wouldn't worry about it. I did find a couple of other issues that are blocking:

1) See my comment about handling hidden bookmarks (that are not in `visibleBookmarks`)

2) The text overflow for longer bookmarks is no longer working as expected.

On this branch:
image

On `main`:
image

**Comment by jbecker01** [comment]
Chrome, FF, and Safari look good on Mac.

**Review by jbecker01 — APPROVED** [review]
Looks good!

**Review by suzubara — APPROVED** [review]
looks awesome!! :shipit:

**Pull request merged**
