### PR TITLE
feat: Update sort by UI on sites & apps

### PR DESCRIPTION
**Pull request by abbyoung**
# SC-1938

## Proposed changes

* Places sort alpha / sort type buttons in a dropdown
* Updates unit tests
* Wraps toggle filter in Launch Darkly so we can test which view should be default
## Reviewer notes

Launch Darkly is set up for Dev, flag named "Sites & Apps Sort View". It returns a string, either SORT_ALPHA or SORT_TYPE (choose from dropdown in LD) and will render that view on page load. To test, log in to LD and turn the feature flag on.

~Still needs a little CSS work (dark mode tweaks, etc) and I have some questions around a11y, too -- batsignal @shkeating!.~

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

---

### As the original developer, I have

- [ ] Met the acceptance criteria
- [ ] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [ ] Followed guidelines for zero-downtime deploys, if applicable
- [ ] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

### By Type

image

image

### Alphabetical
image

image

### CODE REVIEW

**Comment by shkeating** [comment]
@abbyoung we want to hide the 'view by' label and button when the select multiple is enabled. I'd do it myself, but that is a bit outside my my understanding

**Review by gidjin — APPROVED** [review]
Code looks good and works as expected. A thought I had as I did the review is that the sites-and-apps page is doing a lot. Feels like we should consider refactoring at some point in the future. What do you think?

**Comment by abbyoung** [comment]
> Code looks good and works as expected. A thought I had as I did the review is that the sites-and-apps page is doing a lot. Feels like we should consider refactoring at some point in the future. What do you think?

100%. I thought we might've had a tech liability story to work on breaking the page up, but if not, I vote YES.

**Comment by jbecker01** [comment]
Looks good to me!

**Review by shkeating — APPROVED** [review]

**Pull request merged**
