### PR TITLE
feat: Update landing page index styles

### PR DESCRIPTION
**Pull request by jcbcapps**
# SC-2741

## Proposed changes
Adds table to the landing page index

---

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

---

### As the original developer, I have

- [ ] Met the acceptance criteria
- [ ] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [ ] Followed guidelines for zero-downtime deploys, if applicable
- [ ] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

## Screenshots

lp-dark
lp-light

### CODE REVIEW

**Comment by AnnaGingle** [comment]
Hi there @jcbcapps ! I am not seeing any landing pages. Do I need to hook this PR up to the API? to see data? If so, will these instructions work? https://github.com/USSF-ORBIT/ussf-portal-client/pull/1127#issuecomment-1785308651

Screenshot 2023-11-27 at 12 19 52 PM

**Comment by jcbcapps** [comment]
> Hi there @jcbcapps ! I am not seeing any landing pages. Do I need to hook this PR up to the API? to see data? If so, will these instructions work? [#1127 (comment)](https://github.com/USSF-ORBIT/ussf-portal-client/pull/1127#issuecomment-1785308651)

@AnnaGingle This PR uses data from the CMS, so no, the instructions you linked will not be helpful. You'll need to have the latest version of the [CMS](https://github.com/USSF-ORBIT/ussf-portal-cms) on your local machine. After running `yarn services:up`, run `yarn dev` in that repo, navigate to http://localhost:3001 in your browser, and create some landing pages. Let me know if you need more assistance/need to pair.

**Comment by AnnaGingle** [comment]
@jcbcapps Got it working! Thanks

Here is some design feedback (I will circle back when feedback on accessibility)
- The table should have the same corner radius of 4px
Dark mode
- Row 1 should have the bg color `0A1529` (same as all sites & applications)
- Row 2 should have bg color `060C17` (same as all sites & applications
- Row 1 & 2 border color should be `71767A`

Everything else is on point! Good work

**Review by gidjin — APPROVED** [review]
LGTM thanks for making those changes!

**Review by AnnaGingle — APPROVED** [review]
LGTM!

**Pull request merged**
