### PR TITLE
feat: upgraded to react-uswds 6.0.0

### PR DESCRIPTION
**Pull request by gidjin**
# SC-2667

## Proposed changes

Upgrading react-uswds to the latest version so we can make use of the `InPageNavigation` component

---

## Reviewer notes

This upgrade takes us from react-uswds 5.1.1 and uswds 3.5.0 to react-uswds 6.0.0 and uswds 3.6.1. The latter introduced some styling changes that need to be investigated and or fixed. Additionally we needed to switch from the `Dropdown` component that was deprecated to use the `Select` component. This was small change as the former just rendered the latter until it's removal in version 6.0.

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

---

### As the original developer, I have

- [ ] Met the acceptance criteria
- [ ] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [ ] Followed guidelines for zero-downtime deploys, if applicable
- [ ] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

### CODE REVIEW

**Review by shkeating — COMMENTED** [review]
image


only issue I see is the background fill on the pagination component in dark mode. I'll check out the branch and push up a change today

**Comment by shkeating** [comment]
> image
> 
> only issue I see is the background fill on the pagination component in dark mode. I'll check out the branch and push up a change today

this is not happening when I run the storybook. I am currently standing up the app to check it there.

**Comment by shkeating** [comment]
just pushed up a fix

**Review by shkeating — APPROVED** [review]
okay fixed the issue I saw, good to go!

**Review by jcbcapps — APPROVED** [review]

**Pull request merged**
