### PR TITLE
fix: design: dark mode adjustments

### PR DESCRIPTION
**Pull request by shkeating**
# SC-2314

## Proposed changes

- theme adjustments to dark mode, and linking some missed properties to themes, such as the search bar. 
- factors in input from accessibility usability around color contrast on some elements in dark mode. 
-removes aurora (light green) color from dark mode theme and replaces with light variations of ultraviolet
- adjusts interaction patterns to follow same principles:
> - if something is hover/focused in light mode, it should get darker in color
> - if something is hover/focused in dark mode, it should get lighter in color

### Start the system
```sh
yarn services:up
yarn dev
cd ../ussf-portal-cms
yarn dev
```

Login to the portal http://localhost:3000

### Start storybook

```sh
yarn storybook
```

Login to storybook http://localhost:6006, though the command above should open it for you

---

### As the original developer, I have

- [ ] Met the acceptance criteria
- [ ] Created new stories in Storybook if applicable
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated [E2E tests](https://github.com/USSF-ORBIT/ussf-portal)
- [ ] Followed guidelines for zero-downtime deploys, if applicable
- [ ] Use [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) to check for basic a11y issues

### As a reviewer, I have

Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) document.

---

## Screenshots
image
image
image

hover

### CODE REVIEW

**Comment by shkeating** [comment]
updated images to reflect change of colors from `$theme-ultraviolet-` to `$theme-ultraviolet-muted-`

**Review by malworks — APPROVED** [review]
:chef-kiss:

**Review by jcbcapps — APPROVED** [review]
LGTM! Great work!

**Review by gidjin — APPROVED** [review]
LGTM!

**Pull request merged**
